[preface]

== Introduction
The OpenDaylight (ODL) project is an open source, hardware-agnostic platform you can use to virtualize networking services, which is commonly referred to as Software-Defined Networking (SDN). ODL's platform implements SDN, integrating open source, open standards, and open APIs to support a multitude of networking scenarios. Application developers can abstract their networking needs, staying out from under the hood while ODL standards ensure software programs can interoperate and communicate clearly and quickly. 

As a collaborative, open source project, ODL's goal is to accelerate adoption of SDN and Network Functions Virtualization (NFV) with a transparent approach that meets your current networking needs and adapts to changes as requirements and scope evolve. The microservices architecture allows you to control applications, protocols, and plugins and enhances your connections with external customers on the web. The ODL community is comprised of contributors from across the world and has a release cadence of roughly every six months. The current Beryllium release is preceded by Lithium and Helion.  

=== The 10,000' view and what's in it for you
To understand how the platform works at a very high level, ODL has a centralized network controller that oversees all network resources and alone directs all network traffic. Applications are based on a microservices architecture consisting of narrowly-focused, independently deployable services that communicate with each other using the platform's open APIs. With application services decoupled and the ODL controller directing networking, your applications run at higher speeds with increased performance and scalability. 

Now let's take a closer look at the ODL platform. If you're already familiar with it and want to get on with the installation, skip to 
//Installing ODL - clarify title and state it here.

== OpenDaylight platform overview
Here we cover the basics of the the ODL platform, which is based on the the Open Service Gateway Initiative (OSGi), which is a Java framework for developing and deploying modular software programs and libraries. OSGI details:
.Supplies a specification for plugins that defines their life cycle and interactions with other plugins. 
.OSGi is a Java Virtual Machine (JVM)-level service registry for plugins to publish, discover, and bind to services in a service-oriented architecture.

ODL software  consists of software designed to run on a Java Virtual Machine (JVM), and you can use it on any operating system and hardware that has a Java Runtime Environment (JRE) available.

// TODO: uncomment the following lines when we have them to the point we think they're useful.
// OpenDaylight makes use of the following third-party tools:
//
// * *Maven*: OpenDaylight uses Maven for easier build automation. Maven uses pom.xml
// (Project Object Model) to script the dependencies between bundles.
//
// * *OSGi*: OSGi framework is the back-end of OpenDaylight as it allows dynamically
// loading bundles and packages JAR files, and binding bundles together for exchanging
// information.
//
// * *JAVA interfaces*: Java interfaces are usually generated by compiling the YANG project. Java interfaces are used for event listening, specifications, and forming
// patterns. This is the main way in which specific bundles implement call-back functions for events and also to indicate awareness of specific state.
//
// * *REST APIs*: Most of the REST APIs in OpenDaylight are defined using YANG tools and are RESTCONF APIs.
//
// * *Karaf*: TBD

For a more detailed information about OpenDaylight, see the and _OpenDaylight User Guide_, _OpenDaylight
Developer Guide_.

