[preface]

== Introduction
The OpenDaylight (ODL) project is an open source, hardware-agnostic platform you can use to virtualize networking services, which is commonly referred to as Software-Defined Networking (SDN). SDN has more than one method of implementation, and ODL's platform integrates open source, open standards, and open APIs to support SDN for a multitude of networking scenarios.

ODL has a centralized network controller that oversees all network resources and alone directs all network traffic. Applications on the ODL platform are based on a microservices architecture consisting of narrowly-focused, independently deployable services that communicate with each other using ODL's open APIs. With application services decoupled and the ODL controller directing networking, your applications run at higher speeds with increased performance and scalability. 

== OpenDaylight Overview
As a collaborative, open source project, ODL's goal is to accelerate adoption of SDN and Network Functions Virtualization (NFV) with a transparent approach that meets your current networking needs while adapting to changes as requirements and scope evolve. The microservices architecture allows you to control applications, protocols, and plugins and enhance your connections with external customers on the web.



ODL software mainly consists of software designed to run on a
Java Virtual Machine (JVM), and you can use it on any operating system and
hardware that has a Java Runtime Environment (JRE) available.

// TODO: uncomment the following lines when we have them to the point we think they're useful.
// OpenDaylight makes use of the following third-party tools:
//
// * *Maven*: OpenDaylight uses Maven for easier build automation. Maven uses pom.xml
// (Project Object Model) to script the dependencies between bundles.
//
// * *OSGi*: OSGi framework is the back-end of OpenDaylight as it allows dynamically
// loading bundles and packages JAR files, and binding bundles together for exchanging
// information.
//
// * *JAVA interfaces*: Java interfaces are usually generated by compiling the YANG project. Java interfaces are used for event listening, specifications, and forming
// patterns. This is the main way in which specific bundles implement call-back functions for events and also to indicate awareness of specific state.
//
// * *REST APIs*: Most of the REST APIs in OpenDaylight are defined using YANG tools and are RESTCONF APIs.
//
// * *Karaf*: TBD

For a more detailed information about OpenDaylight, see the and _OpenDaylight User Guie_, _OpenDaylight
Developer Guide_.

